FROM registry.redhat.io/rhel10/rhel-bootc:10.2


# openjdk21 will be installed with tomcat
RUN dnf install -y tomcat
RUN systemctl enable tomcat

COPY albumui-1.0-SNAPSHOT.war  /usr/share/tomcat/webapps/albumui.war



