services:
  httpd:
    container_name: httpd
    image: httpd:mod_proxy_cluster
    ports:
      - "8090:8090"
      - "8080:8080"
    networks:
      - web
  tomcat1:
    container_name: tomcat1
    image: jws
    ports:
      - "8081:8080"
    networks:
      - web
  tomcat2:
    container_name: tomcat2
    image: jws
    ports:
      - "8082:8080"
    networks:
      - web 
networks:
  web:
