FROM registry.redhat.io/rhel10/rhel-bootc:10.2

RUN dnf install -y httpd
RUN systemctl enable httpd

RUN dnf -y install mod_proxy_cluster

# unload lbmethod_heartbeat_module, proxy_balancer_module to avoid conflict with mod_proxy_cluster
RUN grep -v proxy_balancer_module  /etc/httpd/conf.modules.d/00-proxy.conf > /etc/httpd/conf.modules.d/00-proxy.conf.new && \
mv /etc/httpd/conf.modules.d/00-proxy.conf.new /etc/httpd/conf.modules.d/00-proxy.conf && \
grep -v lbmethod_heartbeat_module /etc/httpd/conf.modules.d/00-proxy.conf > /etc/httpd/conf.modules.d/00-proxy.conf.new && \
mv /etc/httpd/conf.modules.d/00-proxy.conf.new /etc/httpd/conf.modules.d/00-proxy.conf

COPY mod_proxy_cluster.conf /etc/httpd/conf.d/mod_proxy_cluster.conf
RUN mkdir /var/cache/mod_proxy_cluster && chown -R 1001:0 /var/cache/mod_proxy_cluster
