ProxyPass /albumui balancer://mycluster/albumui lbmethod=byrequests timeout=1
<Proxy balancer://mycluster>
  BalancerMember http://tomcat1:8080 route=tomcat1
  BalancerMember http://tomcat2:8080 route=tomcat2
</Proxy>

<Location /balancer-manager>
SetHandler balancer-manager

Order Deny,Allow
Allow from all
</Location>