ProxyPass /balancer balancer://mycluster lbmethod=byrequests timeout=1
<Proxy balancer://mycluster>
  BalancerMember http://tomcat1:8080 loadfactor=1
  BalancerMember http://tomcat2:8080 loadfactor=1
</Proxy>

<Location /manager>
  SetHandler balancer-manager
</Location>